name: "watch"
version: "0.1.0"
usage: " helm watch --chart <chart> --kinds <kinds> --names <resources> [--release-name [release]] -- [optional args for \"helm template\" command"
description: "watch changes in templates and render respecive manifests"
ignoreFlags: false
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGINS/watch/helm-watch-linux-amd64"
  - os: linux
    arch: arm64
    command: "$HELM_PLUGINS/watch/helm-watch-linux-arm64"
  - os: darwin
    arch: amd64
    command: "$HELM_PLUGINS/watch/helm-watch-darwin-amd64"
  - os: darwin
    arch: arm64
    command: "$HELM_PLUGINS/watch/helm-watch-darwin-arm64"
